spring:
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka
